---
apiVersion: v1
kind: Service
metadata:
  name: proemtheus-operated-nodeport
  namespace: dev
  labels:
    prometheus: dev
spec:
  type: NodePort
  ports:
  - port: 9090
    nodePort: 31000
    targetPort: web
    protocol: TCP
    name: web
  selector:
    app: prometheus
    prometheus: prometheus
