apiVersion: apps/v1
kind: Deployment
metadata:
  name: repository
  namespace: dev
  labels:
    app: repository
    component: repository
    role: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      component: repository
      role: dev
  template:
    metadata:
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/agent-inject-status: "update"
        vault.hashicorp.com/agent-inject-secret-configs: "database/static-creds/configs"
        vault.hashicorp.com/role: "microservice"
        #config.linkerd.io/enable-debug-sidecar: "true"
        #linkerd.io/inject: enabled
      labels:
        component: repository
        role: dev
    spec:
      #securityContext:
      serviceAccountName: microservice
      containers:
        - name: repository
          #securityContext:
          image: "localhost:5000/repository:dev"
          ports:
          - containerPort: 5432
            name: healthcheck
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 100m
              memory: 128Mi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: microservice
  namespace: dev
