# Postgres
dType: "postgres"
dHost: "postgres.storage"
dPort: "5432"
dbName: "configsdb"
maxOpenConns: 50
maxIdleConns: 20
dUser: "postgres"
dPass: "postgres"
# Use vault-k8s to get credentials instead of 
# credentials above or environment variables.
vault: true
# RabbitMQ
amqpAddr: "amqp://user:pass@rabbitmq.storage:5672"
