apiVersion: v1
kind: Service
metadata:
  namespace: dev
  name: api
  labels:
    component: api
    role: dev
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 32000
      protocol: TCP
      name: http
  selector:
    component: api
    role: dev
